# Generated by Django 3.1.2 on 2021-11-12 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_no', models.IntegerField()),
                ('balance_amount', models.FloatField()),
                ('initialized_at', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 27, 34, 247855, tzinfo=utc))),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(null=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=100)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.wallet')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=100)),
                ('deposited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer')),
                ('for_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.wallet')),
            ],
        ),
    ]
