# Generated by Django 3.1.2 on 2021-11-12 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='initialized_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 17, 12, 22, 369853, tzinfo=utc)),
        ),
    ]
